### ISSUE TITLE
Configuration failed: Data protection failed

### ISSUE THREAD

**Issue by Mahmoud87** [oblique/dockerfiles#1]
Hi mate. first thanks for the awesome docker, however I have an issue when I try to add any tracker. I get this error message 
![jackett1](https://cloud.githubusercontent.com/assets/20716439/21038746/203aacc0-be28-11e6-9252-229d40c134dd.jpg)

and here is some logs
![jackett2](https://cloud.githubusercontent.com/assets/20716439/21038753/2c17eed6-be28-11e6-900b-27c2c559a8d3.jpg)

I wish you will be able to help me out with this one. I have also checked on Jackett git the issue isn't globally.
Thanks

**Comment by oblique** [comment]
How do you run it? Do you set `PUID` and `PGID`?

**Comment by Mahmoud87** [comment]
Hey mate mate, I use an account with UID1000 and GID1000.

**Comment by oblique** [comment]
I don't have such a problem. Maybe the partition that `config` dir exists, is mounted as read-only. Check your server. Also try to manually create a file in the `config` dir.

**Comment by Mahmoud87** [comment]
Thanks for getting back to me. The partition wasn't read only. I have already used another image and it worked fine, but thanks anyway.

**Comment by oblique** [comment]
No problem. I'm closing the issue.
