### ISSUE TITLE
airvpn socks proxy

### ISSUE THREAD

**Issue by josefstr** [oblique/dockerfiles#3]
I've started airvpn docker as you suggest with:
```
docker run -d \
    --cap-add=NET_ADMIN \
    -p 127.0.0.1:1080:1080 \
    -v /your_airvpn_configs:/airvpn \
    -e COUNTRY=se \
    oblique/airvpn
```
I can see that I'm connected to airvpn, but I cannot use the socks 5 proxy.
my docker ip is 172.17.0.1, so I've thought I can access the proxy with:
`# export {http,https,ftp}_proxy="172.17.0.1:1080"`
`# wget https://git.kernel.org/torvalds/t/linux-4.13-rc2.tar.gz`
--2017-07-27 11:51:50--  https://git.kernel.org/torvalds/t/linux-4.13-rc2.tar.gz
Connecting to 172.17.0.1:1080... failed: Connection refused.

I'm not sure what I'm missing? Could you help me? Thanks.

**Comment by oblique** [comment]
Since you start it with `-p 127.0.0.1:1080:1080` you need to set the proxy as `127.0.0.1:1080`.

**Comment by josefstr** [comment]
but then I recieve:
```
wget http://git.kernel.org/torvalds/t/linux-4.13-rc2.tar.gz                                                                                                                    :(
--2017-07-27 12:39:32--  http://git.kernel.org/torvalds/t/linux-4.13-rc2.tar.gz
Connecting to 127.0.0.1:1080... connected.
Proxy request sent, awaiting response... No data received.
Retrying.
```

actually I'm trying to use the airvpn proxy in firefox, but I'm testing the connection on the command line. Both are not connecting to the proxy.

**Comment by josefstr** [comment]
well it was my fault.. I didn't use socks5 proxy only in wget and firefox settings ...
